title: Joonyoung (Aaron)'s Website
description: personal website
theme: just-the-docs

url: https://n99joon.github.io

aux_links:
  GitHub: https://github.com/n99joon
  Google Scholar: https://scholar.google.com/citations?user=P_dzLk8AAAAJ&hl=en&oi=ao
  CV: /assets/files/Aaron_PhD_CV.pdf

# math: katex
math: mathjax

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: mathjax

plugins:
  - jekyll-last-modified-at

search_enabled: false
# navigation_order:
#   - title: Home
#   - title: paper
#   - title: Useful Links
#     children: 
#     - title: Math