title: Joonyoung (Aaron)'s Blog
description: personal blog
theme: just-the-docs

url: https://n99joon.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"