title: Joonyoung (Aaron)'s Blog
description: personal blog
theme: just-the-docs

url: https://n99joon.github.io

aux_links:
  Github: github.com/n99joon

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"