title: Joonyoung (Aaron)'s Website
description: personal website
theme: just-the-docs

url: https://n99joon.github.io

aux_links:
  Github: https://github.com/n99joon

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"